polkasync: repair error code

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -171,13 +171,16 @@ polkadot:sync:stop:
     variables:
       - $POLKASYNC == "stop"
   script:
-    - PAYLOAD="{\"jsonrpc\":\"2.0\",\"method\":\"system_health\",\"params\":[],\"id\":0}"
     - |
       set -x
+      PAYLOAD="{\"jsonrpc\":\"2.0\",\"method\":\"system_health\",\"params\":[],\"id\":0}"
       get_out () {
         kill %1 # stop port-forwarding
         kubectl -n "${KUBE_NAMESPACE}" delete -f polkasync/deployment.yaml
-        test -f FAILED && exit 1 # alert somebody
+        case "$1" in
+          (FAIL) echo "a check failed - alert somebody"; exit 1;;
+          (*)    echo "chain seems to be synced well";;
+        esac
       }
 
       kubectl -n ${KUBE_NAMESPACE} port-forward svc/polkasync-rpc 9933:9933 &
@@ -187,15 +190,14 @@ polkadot:sync:stop:
           -H "Content-Type: application/json" \
           -X POST localhost:9933 -o out.json
         
-        grep -q -e isSyncing -e peers out.json || get_out
-        jq -e '.result.isSyncing == false' out.json || get_out
-        jq -e '.result.peers > 2' out.json || get_out
+        grep -q -e isSyncing -e peers out.json || get_out FAIL
+        jq -e '.result.isSyncing == false' out.json || get_out FAIL
+        jq -e '.result.peers > 2' out.json || get_out FAIL
         sleep 30
       done
       rm -f out.json
+      get_out
       set +x
-    - test -f FAILED && echo FAILED || echo SUCCESS
-    - get_out
 
 
 
